server:
  port: 9001
spring:
  application:
    name: SERVICE-REGISTRY
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:9001/eureka/
  server:
    enable-self-preservation: false
