server:
  port: 9002
spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - ${CONFIG_REPO_LOCATION:file:../vscm-configuration/configurations}
            - ${CONFIG_REPO_LOCATION:file:../vscm-configuration/configurations}/platform
            - ${CONFIG_REPO_LOCATION:file:../vscm-configuration/configurations}/services
            - classpath:/configurations
            - classpath:/configurations/platform
            - classpath:/configurations/services
management:
  endpoints:
    web:
      exposure:
        include: health,info
