server:
  port: 0
spring:
  application:
    name: BILLING-SERVICE
  datasource:
    url: ${BILLING_DB_URL:jdbc:mysql://localhost:16500/autocare_billing?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${BILLING_DB_USER:root}
    password: ${BILLING_DB_PASSWORD:mysql}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
