server:
  port: 0
spring:
  application:
    name: WORK-ORDER-SERVICE
  datasource:
    url: ${WORKORDER_DB_URL:jdbc:postgresql://localhost:15500/autocare_workorder}
    username: ${WORKORDER_DB_USER:postgres}
    password: ${WORKORDER_DB_PASSWORD:psql}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
